/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CampaignFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DURATION"
      | "MAX_GOAL"
      | "MIN_GOAL"
      | "accumulatedFees"
      | "campaigns"
      | "campaignsByCreator"
      | "createCampaign"
      | "getActiveCampaigns"
      | "getAllCampaigns"
      | "getCampaignAt"
      | "getCampaignCount"
      | "getCampaignsByCreator"
      | "getConfig"
      | "getCreatorCampaignCount"
      | "idrxToken"
      | "owner"
      | "pauseCampaign"
      | "platformFee"
      | "renounceOwnership"
      | "totalCampaigns"
      | "transferOwnership"
      | "unpauseCampaign"
      | "updatePlatformFee"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignPaused"
      | "CampaignUnpaused"
      | "FeesWithdrawn"
      | "OwnershipTransferred"
      | "PlatformFeeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_GOAL", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_GOAL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignsByCreator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignsByCreator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCreatorCampaignCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "idrxToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseCampaign",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseCampaign",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_GOAL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_GOAL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorCampaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idrxToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaign: AddressLike,
    creator: AddressLike,
    title: string,
    goal: BigNumberish,
    deadline: BigNumberish,
    campaignId: BigNumberish
  ];
  export type OutputTuple = [
    campaign: string,
    creator: string,
    title: string,
    goal: bigint,
    deadline: bigint,
    campaignId: bigint
  ];
  export interface OutputObject {
    campaign: string;
    creator: string;
    title: string;
    goal: bigint;
    deadline: bigint;
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignPausedEvent {
  export type InputTuple = [campaign: AddressLike];
  export type OutputTuple = [campaign: string];
  export interface OutputObject {
    campaign: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignUnpausedEvent {
  export type InputTuple = [campaign: AddressLike];
  export type OutputTuple = [campaign: string];
  export interface OutputObject {
    campaign: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CampaignFactory extends BaseContract {
  contractName: "CampaignFactory";

  connect(runner?: ContractRunner | null): CampaignFactory;
  waitForDeployment(): Promise<this>;

  interface: CampaignFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_GOAL: TypedContractMethod<[], [bigint], "view">;

  MIN_GOAL: TypedContractMethod<[], [bigint], "view">;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  campaignsByCreator: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _goal: BigNumberish,
      _duration: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getActiveCampaigns: TypedContractMethod<[], [string[]], "view">;

  getAllCampaigns: TypedContractMethod<[], [string[]], "view">;

  getCampaignAt: TypedContractMethod<[_index: BigNumberish], [string], "view">;

  getCampaignCount: TypedContractMethod<[], [bigint], "view">;

  getCampaignsByCreator: TypedContractMethod<
    [_creator: AddressLike],
    [string[]],
    "view"
  >;

  getConfig: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        _idrxToken: string;
        _minGoal: bigint;
        _maxGoal: bigint;
        _maxDuration: bigint;
        _platformFee: bigint;
        _totalCampaigns: bigint;
      }
    ],
    "view"
  >;

  getCreatorCampaignCount: TypedContractMethod<
    [_creator: AddressLike],
    [bigint],
    "view"
  >;

  idrxToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseCampaign: TypedContractMethod<
    [_campaign: AddressLike],
    [void],
    "nonpayable"
  >;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalCampaigns: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseCampaign: TypedContractMethod<
    [_campaign: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlatformFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_GOAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_GOAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "campaignsByCreator"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _goal: BigNumberish,
      _duration: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveCampaigns"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllCampaigns"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCampaignAt"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCampaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaignsByCreator"
  ): TypedContractMethod<[_creator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, bigint, bigint] & {
        _idrxToken: string;
        _minGoal: bigint;
        _maxGoal: bigint;
        _maxDuration: bigint;
        _platformFee: bigint;
        _totalCampaigns: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorCampaignCount"
  ): TypedContractMethod<[_creator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "idrxToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseCampaign"
  ): TypedContractMethod<[_campaign: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalCampaigns"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseCampaign"
  ): TypedContractMethod<[_campaign: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignPaused"
  ): TypedContractEvent<
    CampaignPausedEvent.InputTuple,
    CampaignPausedEvent.OutputTuple,
    CampaignPausedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignUnpaused"
  ): TypedContractEvent<
    CampaignUnpausedEvent.InputTuple,
    CampaignUnpausedEvent.OutputTuple,
    CampaignUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(address,address,string,uint256,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignPaused(address)": TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;
    CampaignPaused: TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;

    "CampaignUnpaused(address)": TypedContractEvent<
      CampaignUnpausedEvent.InputTuple,
      CampaignUnpausedEvent.OutputTuple,
      CampaignUnpausedEvent.OutputObject
    >;
    CampaignUnpaused: TypedContractEvent<
      CampaignUnpausedEvent.InputTuple,
      CampaignUnpausedEvent.OutputTuple,
      CampaignUnpausedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
