/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleCampaignSol from "./SimpleCampaign.sol";
export type { simpleCampaignSol };
export type { SimpleFactory } from "./SimpleFactory";
