/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleCampaign } from "./SimpleCampaign";
export type { SimpleFactory } from "./SimpleFactory";
