/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleCampaignSol from "./SimpleCampaign.sol";
export { SimpleFactory__factory } from "./SimpleFactory__factory";
