/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleCampaign__factory } from "./SimpleCampaign__factory";
export { SimpleFactory__factory } from "./SimpleFactory__factory";
